version: '3'
volumes:
  postgres-data:
  pgadmin-data:

services:
  postgres:
    container_name: Postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: image_storage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: PgAdmin
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin